from typing import List, Optional, Union
from pydantic import BaseModel, Field, field_validator

class ChatRequest(BaseModel):
    question: str = Field(
        ...,
        description="User question regarding Indian Standards and BIS services",
        example="What is hallmarking?"
    )
    response_language: Optional[str] = Field(
        None,
        description="Target response language: English, Tamil, Hindi, or Auto",
        example="Tamil"
    )


    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Question cannot be empty or contain only whitespace.")
        v_stripped = v.strip()
        if len(v_stripped) > 1000:
            raise ValueError("Question exceeds maximum length of 1000 characters.")
        return v_stripped

class SourceItem(BaseModel):
    document: str = Field(..., description="Source PDF document filename")
    document_title: Optional[str] = Field(None, description="Human readable document title")
    page: Union[int, str] = Field(..., description="Page number where evidence was found")
    category: Optional[str] = Field(None, description="Document category tag")
    is_number: Optional[str] = Field(None, description="Indian Standard (IS) number if present")
    clause_number: Optional[str] = Field(None, description="Clause number if present")
    section_number: Optional[str] = Field(None, description="Section number if present")
    scheme_number: Optional[str] = Field(None, description="Conformity Assessment Scheme number if present")
    qco_reference: Optional[str] = Field(None, description="Quality Control Order reference if present")
    relevance_score: Optional[float] = Field(None, description="Vector L2 similarity score (lower is better)")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="Grounded markdown formatted answer generated by Gemini")
    evidence_status: str = Field(..., description="Evidence confidence status (High Confidence, Moderate Confidence, Limited Evidence)")
    sources: List[SourceItem] = Field(default_factory=list, description="List of source document citations")
    response_language: Optional[str] = Field("English", description="Language of the returned response")
    execution_time_seconds: Optional[float] = Field(None, description="Total backend execution time in seconds")
    timings: Optional[dict] = Field(None, description="Detailed diagnostic timing breakdown in seconds")

class HealthResponse(BaseModel):
    status: str = Field("ok", example="ok")
    service: str = Field("PURIVU", example="PURIVU")
    rag: str = Field("ready", example="ready")
    gemini: Optional[str] = Field("configured", example="configured")
    text_model: Optional[str] = Field(None, description="Configured Gemini text model name")
    vision_model: Optional[str] = Field(None, description="Configured Gemini vision model name")
    corpus_chunk_positions: Optional[int] = Field(2239, description="Original total corpus chunk positions")
    unique_indexed_chunks: Optional[int] = Field(2235, description="Unique chunk embeddings stored in FAISS index")
    total_chunks: Optional[int] = Field(None, description="Number of indexed chunks loaded in FAISS")

class ProductInfo(BaseModel):
    name: str = Field(..., description="Likely name of the product identified by vision model")
    category: str = Field(..., description="General category or classification of the product")
    description: str = Field(..., description="Visual characteristics and description of the product")
    confidence: str = Field(..., description="Vision identification confidence: High, Moderate, or Low")

class VisionResponse(BaseModel):
    product: ProductInfo = Field(..., description="Identified product details")
    answer: str = Field(..., description="Grounded markdown formatted answer generated by Gemini from BIS RAG")
    evidence_status: str = Field(..., description="RAG Evidence confidence status")
    sources: List[SourceItem] = Field(default_factory=list, description="List of source document citations")

class MetricsResponse(BaseModel):
    status: str = Field("ok", example="ok")
    total_queries: int = Field(0, description="Total queries processed since startup")
    cache_hits: int = Field(0, description="Total cache hits")
    cache_hit_rate_pct: float = Field(0.0, description="Cache hit percentage")
    avg_latency_sec: float = Field(0.0, description="Average response latency in seconds")
    p50_latency_sec: float = Field(0.0, description="50th percentile (median) latency in seconds")
    p95_latency_sec: float = Field(0.0, description="95th percentile latency in seconds")
    avg_retrieval_sec: float = Field(0.0, description="Average FAISS retrieval time in seconds")
    avg_gemini_sec: float = Field(0.0, description="Average Gemini generation time in seconds")
    total_chunks: int = Field(0, description="Total chunks in active FAISS index")
    index_version: str = Field("v1", description="Active vector index version hash")
    query_paths: Optional[dict] = Field(default_factory=dict, description="Distribution of FAST vs DEEP query paths")


